export const ep = {
  auth: {
    login:    "/auth/login",
    register: "/auth/register",
    refresh:  "/auth/refresh",
    logout:   "/auth/logout",
  },
  tournaments: {
    list:        "/tournaments",
    get:         (id: string) => `/tournaments/${id}`,
    users:       (id: string) => `/tournaments/${id}/users`,
    user:        (id: string, userId: string) => `/tournaments/${id}/users/${userId}`,
    players:     (id: string) => `/tournaments/${id}/players`,
    player:      (id: string, playerId: string) => `/tournaments/${id}/players/${playerId}`,
    pairs:       (id: string) => `/tournaments/${id}/pairs`,
    pair:        (id: string, pairId: string) => `/tournaments/${id}/pairs/${pairId}`,
    teams:       (id: string) => `/tournaments/${id}/teams`,
    team:        (id: string, teamId: string) => `/tournaments/${id}/teams/${teamId}`,
    teamMembers: (id: string, teamId: string) => `/tournaments/${id}/teams/${teamId}/members`,
    teamMember:  (id: string, teamId: string, playerId: string) => `/tournaments/${id}/teams/${teamId}/members/${playerId}`,
    courts:      (id: string) => `/tournaments/${id}/courts`,
    court:       (id: string, courtId: string) => `/tournaments/${id}/courts/${courtId}`,
    categories:  (id: string) => `/tournaments/${id}/categories`,
    category:    (id: string, catId: string) => `/tournaments/${id}/categories/${catId}`,
    matches:     (id: string) => `/tournaments/${id}/matches`,
    match:       (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}`,
    matchStatus: (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}/status`,
    matchOrder:         (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}/order`,
    matchScheduledTime: (id: string, matchId: string) => `/tournaments/${id}/matches/${matchId}/scheduled-time`,
    matchHistory:(id: string) => `/tournaments/${id}/matches/history`,
    draws:       (id: string) => `/tournaments/${id}/draws`,
    info:        (id: string) => `/tournaments/${id}/info`,
    infoAttachments: (id: string) => `/tournaments/${id}/info/attachments`,
    infoAttachment:  (id: string, attachId: string) => `/tournaments/${id}/info/attachments/${attachId}`,
  },
  draws: {
    get:           (drawId: string) => `/draws/${drawId}`,
    confirm:       (drawId: string) => `/draws/${drawId}/confirm`,
    autoFill:      (drawId: string) => `/draws/${drawId}/auto-fill`,
    clearNonSeeded:(drawId: string) => `/draws/${drawId}/clear-non-seeded`,
    slot:          (drawId: string, slotId: string) => `/draws/${drawId}/slots/${slotId}`,
    slotTeam:      (drawId: string, slotId: string) => `/draws/${drawId}/slots/${slotId}/team`,
    addToOop:      (drawId: string, round: number) => `/draws/${drawId}/rounds/${round}/add-to-oop`,
    // RR用
    generateMatches: (drawId: string) => `/draws/${drawId}/generate-matches`,
    standings:       (drawId: string) => `/draws/${drawId}/standings`,
    rrAddToOop:      (drawId: string) => `/draws/${drawId}/add-to-oop`,
    matchAddToOop:   (drawId: string, matchId: string) => `/draws/${drawId}/matches/${matchId}/add-to-oop`,
    // team_battle用
    teamStandings: (drawId: string) => `/draws/${drawId}/team-standings`,
  },
  encounters: {
    list:        (tournamentId: string, categoryId: string) => `/tournaments/${tournamentId}/categories/${categoryId}/encounters`,
    create:      (tournamentId: string, categoryId: string) => `/tournaments/${tournamentId}/categories/${categoryId}/encounters`,
    get:         (encounterId: string) => `/encounters/${encounterId}`,
    updateRubber:   (encounterId: string, matchId: string) => `/encounters/${encounterId}/rubbers/${matchId}`,
    completeRubber: (encounterId: string, matchId: string) => `/encounters/${encounterId}/rubbers/${matchId}/complete`,
    addToOop:    (encounterId: string) => `/encounters/${encounterId}/oop`,
    retire:      (encounterId: string) => `/encounters/${encounterId}/retire`,
  },
  master: {
    players: "/players",
    player:  (id: string) => `/players/${id}`,
    teams:   "/teams",
    team:    (id: string) => `/teams/${id}`,
    pairs:   "/pairs",
    pair:    (id: string) => `/pairs/${id}`,
  },
  csv: {
    template:      (type: string) => `/csv/templates/${type}`,
    preview:       (type: string) => `/csv/preview/${type}`,
    importPlayers: "/csv/import/players",
    importTeams:   "/csv/import/teams",
    importPairs:   "/csv/import/pairs",
  },
  view: {
    get:  (token: string) => `/view/${token}`,
    info: (token: string) => `/view/${token}/info`,
  },
};
